Repository Fire-Oceann/CS-Space, pull requests merged in 2022-10, with the labels that each got.

#53 [DOC] Spelling mistakes fixed in introduction documentation page
  content/docs/01-introduction.mdx
Labels: 🐛 bug, hacktoberfest, hacktoberfest-accepted

#60 Add Italian to README-IT.md
  README/README-IT.md
Labels: ✅ done, Translate, hacktoberfest, hacktoberfest-accepted

#64 Add npm as prerequisite in README
  README.md
Labels: 🐛 bug, ✅ done, hacktoberfest, hacktoberfest-accepted

#62 Changed Language to Russian
  README/README-RU.md
Labels: ✅ done, Translate, hacktoberfest, hacktoberfest-accepted

#66 [FEATURE] Translate the README file to Turkish
  README/README-TR.md
Labels: ✅ done, Translate, hacktoberfest, hacktoberfest-accepted

#65 [Feature] Translated added German language on Readme file
  README/README-DE.md
Labels: ✅ done, Translate, hacktoberfest, hacktoberfest-accepted

#69 [ALGORITHM] - Analysis Of Loops doc is completed
  content/algorithms/analysis-of-algorithms/06-analysis-of-loops.mdx
  content/algorithms/images/06-analysis-of-loops.png
Labels: ✅ done, hacktoberfest, hacktoberfest-accepted
